import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import LoaderContext from "../context/LoaderContext";
import AuthContext from "../context/AuthContext";
import Loader from "../components/Loader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary min-h-screen  text-white ">
        <LoaderContext>
          <AuthContext>
            <Navbar />
              {children}
            <Footer /> 
{/*             <Loader />
 */}          </AuthContext>
        </LoaderContext>
      </body>
    </html>
  );
}
